spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zakupki
    password: 12345
    username: root
    hikari:
      leak-detection-threshold: 45000

homyakin:
  zakupki:
    ftp:
      url: "ftp.zakupki.gov.ru"
      login: "fz223free"
      password: "fz223free"
    app:
      max-threads: 7


